import Head from 'next/head'
import {BsFillMoonStarsFill, BsCode} from 'react-icons/bs';
import {AiFillHome, AiFillGithub, AiFillLinkedin, AiFillTwitter} from 'react-icons/ai';
import Image from 'next/image';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nicholas Fu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-10 flex justify-between">
            <div className="bg-gradient-to-b from-cyan-200 to-teal-400 rounded-full w-16 h-16 relative overflow-hidden">
              <Image src='/../public/wave.png' layout="fill" objectFit="cover" alt="wave"/>
            </div>
            <ul className="flex items-center gap-8">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-xl dark:text-gray-300"/></li>
              <li>
                <a className="bg-gradient-to-br from-cyan-200 to-teal-400 px-4 py-2 rounded-md font-light" href="#">Resume</a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 lg:flex gap-10">
            <div className="rounded-full w-80 h-80 relative overflow-hidden mx-auto mb-10">
              <Image src='/../public/me.jpeg' layout="fill" objectFit='cover' alt="me"/>
            </div>
            <div>
              <h2 className="text-5xl py-4 text-teal-600 font-medium dark:text-teal-300">Nicholas Fu</h2>
              <h3 className="text-xl dark:text-gray-300">Radical thinker, inspired developer.</h3>
              <p className="text-md py-6 text-gray-800 max-w-xl mx-auto dark:text-gray-400">
                Welcome! I&apos;m an aspiring software engineer currently studying computer science and political science 
                at Swarthmore College &apos;25.
              </p>
              <div className="text-3xl text-gray-800 flex justify-center gap-8 dark:text-gray-300">
                <AiFillLinkedin className="cursor-pointer"/>
                <AiFillGithub className="cursor-pointer"/>
              </div>
            </div>
          </div>
        </section>

        <section> 
        </section>
      </main>
    </div>
  )
}
